### ISSUE TITLE
如何让输入候选词部分横着显示

### ISSUE THREAD

**Issue by red-blakTree** [rime/rime-pinyin-simp#29]
ibus-rime可以设置为这个
```
style:
  cursor_type: insert
  horizontal: true
  inline_preedit: true
  preedit_style: composition
```
这个怎么设置
